### ISSUE TITLE
Yêu cầu chức năng

### ISSUE THREAD

**Issue by ducthienute** [ducthienute/ProjectSE25#4]

**Comment by dannk1312** [comment]
1. Đăng kí, đăng nhập:
Giúp người dùng tạo tài khoán, truy xuất vào đúng hồ sơ cá nhân. Các thông tin sức khỏe cũng được lưu trữ cho từng người dùng.
Nút đăng kí, đăng nhập sẽ xuất hiện ở màn hình chính ngay khi người dùng vào ứng dụng.
Khi chọn chức năng đăng kí, ứng dụng chuyển qua màn hình mới để người dùng điền tất cả các thông tin cá nhân cần thiết: tên đăng nhập, mật khẩu, xác nhận mật khẩu, họ tên, ngày sinh, giới tính, số điện thoại, email, chiều cao, cân nặng... nếu 1 trong các thông tin được điền vào không chính xác như yêu cầu của hệ thống chẳng hạn như điền thiếu, sai kiểu dữ liệu thì sẽ thông báo cho người dùng để nhập lại.
Việc đăng nhập sẽ thành công nếu người dùng đã có tài khoản và điền đúng tên đăng nhập và mật khẩu. Nếu sai hoặc điền thiếu, thông báo cho người dùng đăng nhập lại. Nếu thành công, ứng dụng sẽ vào trang cá nhân của người dùng để người dùng thao tác.

**Comment by dannk1312** [comment]
2. Chức năng nhập chỉ số sức khỏe cho từng ngày:
Người dùng chọn vào nút theo dõi, ứng dụng sẽ chuyển sang trang mới, trang này cho phép người dùng điền tất cả các thông tin về sức khỏe như cân nặng, chiều cao, nhịp tim vào buổi sáng, huyết áp, các số đo 3 vòng...

**Comment by dannk1312** [comment]
3. Tính toán chỉ số BMI, calo:
Người dùng nhập trọng lượng cơ thể, chiều cao, các loại thực phẩm 1 cách chi tiết như số bữa ăn, thành phần, khối lượng. Hệ thống sẽ tự động tính toán dựa theo công thức chuẩn của y khoa để đưa ra các mức đánh giá về cơ thể cũng như đưa ra lời khuyên nên tăng hay giảm cân, lượng calo cần đốt cháy.

**Comment by dannk1312** [comment]
4. Các bài tập:
Giúp người dùng quản lí được khung giờ luyện tập, bài tập mẫu.
