### ISSUE TITLE
Yêu cầu phi chức năng

### ISSUE THREAD

**Issue by ducthienute** [ducthienute/ProjectSE25#5]

**Comment by TamHuynhTee** [comment]
Yêu cầu phi chức năng bao gồm: 
- Yêu cầu về ứng dụng: giao diện dễ nhìn, thanh menu đơn giản, font chữ đẹp, gây thiện cảm với người dùng, ...
- Yêu cầu về hiệu quả sử dụng: Ứng dụng phải đáp ứng tốt nhu cầu sử dụng của khách hàng, bảo đảm an toàn dữ liệu khách quan
- Yêu cầu về chức năng: 
  + Chức năng chẩn đoán các thông số sức khỏe dựa trên cân nặng và chiều cao
  + Thông báo lịch trình tập luyện sức khỏe và nhắc nhở cho người sử dụng hàng ngày
  + Đề xuất thực đơn ăn kiêng, giảm cân, duy trì sức khỏe tốt dựa trên thể trạng sức khỏe hiện tại
- Yêu cầu về hiệu năng: Ứng dụng chạy mượt mà, không phát sinh lỗi trong quá trình sử dụng.
- Yêu cầu về không gian: Ứng dụng có size không quá lớn khoảng dưới 50MB
