### ISSUE TITLE
Use Case diagram

### ISSUE THREAD

**Issue by ducthienute** [ducthienute/ProjectSE25#6]
Tạo sơ đồ đặc tả yêu cầu của phần mềm

**Comment by dannk1312** [comment]
[Usecase.docx](https://github.com/ducthienute/ProjectSE25/files/6247401/Usecase.docx)

**Comment by TamHuynhTee** [comment]
[USECASE_DIAGRAM.docx](https://github.com/ducthienute/ProjectSE25/files/6291347/USECASE_DIAGRAM.docx)
